#ifndef _SYSTEM_DEFINES_H
#define _SYSTEM_DEFINES_H

#define CLIENT_MODE_PASSIVE 0
#define CLIENT_MODE_ACTIVE 1

#define BUILDING_CONSTRUCTOR 0

#define GRASS_TILE 0
#define DIRT_TILE 1

#define UNIT_TANK 0

#endif